# fly.toml app configuration file generated for tevkil on 2025-10-24T05:36:04+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tevkil'
primary_region = 'ams'

[build]

[env]
  FLASK_ENV = 'production'
  PORT = '8080'
  PYTHONUNBUFFERED = '1'

[mounts]
  source = "tevkil_storage"
  destination = "/app/static/uploads"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/"

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 250
    soft_limit = 200

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
